services:
  app.auto_scout_scraper.service:
    class: App\Service\Commands\AutoScout24Scraper
#    public: true
    arguments:
      - "@doctrine.orm.entity_manager"
    tags:
      - { name: 'app.scraper' }

  app.dummy_scraper.service:
    class: App\Service\Commands\DummyScraper
#    public: true
    arguments:
      - "@doctrine.orm.entity_manager"
    tags:
      - { name: 'app.scraper' }