imports:
    - { resource: parameters.yml }
    - { resource: manager.yml }
    - { resource: scrapers.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Commands\ScraperCommand:
        class: App\Commands\ScraperCommand
        arguments:
            - "@app.scraper.manager"
        tags:
            - { name: 'console.command' , command: 'app:scraper' }